#!/usr/bin/env perl

###############################################################################
# slt - Scott's lookup table
#
# Usage: slt /tmp/data.txt lookup_key
#
# Data store should be a text file in .ini style file or key/value separated
# by either '=' or ':'
###############################################################################

use strict;
use warnings;
use v5.16;
use Getopt::Long;

my $SLT_ENV_VAR     = 'SLT_FILE';
my $DS_DEFAULT_FILE = $ENV{HOME} . "/.slt.txt";

###############################################################################

my $debug = 0;
GetOptions(
	'debug' => \$debug,
);

my $is_interactive = (-t STDOUT != 0);
my $warn_str       = color("red", 'Warning:');
my $reset          = color("reset");
my $VERSION        = 'v0.3.2';

# Get the data source file and filter
my ($file, $filter, $ds_source) = get_ds_file_and_filter();

###############################################################################
###############################################################################

handle_debug($ds_source);

if (!@ARGV && !$debug) {
	die(usage());
}

# Make sure the input file is readable
if ($file && !-r $file) {
	printf STDERR ("%sError:%s unable to read '%s'\n", color('red'), color('reset'), $file);

	exit(11);
}

# Read the input data source into a hash
my $data = parse_ini($file);

if ($debug) {
	output_ds($data);
	exit(1);
} elsif ($filter) {
	my $x = $data->{$filter} || "";

	if ($x) {
		print "$x\n";
	} else {
		print STDERR "$warn_str '$filter' not found\n";
		exit(9);
	}
} elsif (!$filter) {
	print STDERR "$warn_str No filter specified\n\n";
	output_ds($data);
	exit(1);
}

###############################################################################
###############################################################################

sub output_ds {
	my $x = shift();

	my @keys = sort keys %$x;

	# We add 16 because the ANSI coloring is 15 chars
	my $max  = max_length(@keys) + 16;

	foreach my $key (@keys) {
		my $value = $x->{$key};

		my $key = color(208, $key);
		$value  = color('yellow', $value);

		printf("%${max}s => %s\n", $key, $value);
	}

	return 1;
}

sub max_length {
	my $max = 0;

	foreach my $item (@_) {
		my $len = length($item);
		if ($len > $max) {
			$max = $len;
		}
	}

	return $max;
}

sub parse_ini {
	open (my $INI, "<", $_[0]) or return undef;

	my $ret     = {};
	my $section = "";

	while (my $line = readline($INI)) {
		if ($line =~ /^\[(.+?)\]/) { # Section heading
			$section = $1;
		} elsif ($line =~ /^(\w.*?)\s*[:=]\s*"?(.*?)"?\s*$/) { # Key/Value pair
			my $key   = $1;
			my $value = $2;

			if ($section) {
				$ret->{"$section.$key"} = $value;
			} else {
				$ret->{$key} = $value;
			}
		}
	}

	return $ret;
}

sub trim {
	my ($s) = (@_, $_); # Passed in var, or default to $_
	if (!defined($s) || length($s) == 0) { return ""; }
	$s =~ s/^\s*//;
	$s =~ s/\s*$//;

	return $s;
}

# String format: '115', '165_bold', '10_on_140', 'reset', 'on_173', 'red', 'white_on_blue'
sub color {
	my ($str, $txt) = @_;

	if (-t STDOUT == 0 || $ENV{NO_COLOR}) { return $txt // ""; } # No interactive terminal
	if (!length($str) || $str eq 'reset') { return "\e[0m";    } # No string = RESET

	# Some predefined colors/commands
	my %color_map = qw(red 160 blue 27 green 34 yellow 226 orange 214 purple 93 white 15 black 0);
	my %cmd_map   = qw(bold 1 italic 3 underline 4 blink 5 inverse 7);

	# Pre-process the string.
	$str =~ s/on_/-/;                              # "on_" becomes a negative number
	$str =~ s|([A-Za-z]+)|$color_map{$1} // $1|eg; # command number

	my @parts = split("_", $str);
	foreach my $p (@parts) {
		my $cmd_num = $cmd_map{$p // 0};

		if    ($cmd_num)                      { $p = $cmd_num;  }
		elsif (defined($p) && $p =~ /^-(.+)/) { $p = "48;5;$p"; }
		elsif (defined($p))                   { $p = "38;5;$p"; }
	}

	my $ret = "\e[" . join(";", @parts) . "m";

	if (defined($txt)) { $ret .= $txt . "\e[0m"; }

	return $ret;
}

sub usage {
	my $str = color('228', "SLT version: $VERSION\n\n");
	$str   .= color('159', "Usage: ");
	$str   .= "$0 [input.txt] lookup_key\n";
	$str   .= "\n";
	$str   .= "Info: If input is not specified " . color('193', "~/.slt.txt") . " is used\n";

	return $str;
}

sub handle_debug {
	my $source = shift();

	if ($debug) {
		# Output the source fo the datasource file
		printf("%sDataSource:%s %s\n", color('yellow'), color('reset'), $source);

		# Output the path to the file
		printf("%sFile      :%s %s\n\n", color('yellow'), color('reset'), $file);
	}

	return 1;
}

# Extract the data store file and filter from appropriate places: ARGV/ENV/Default
sub get_ds_file_and_filter {
	my $file   = $ARGV[0] || "";
	my $filter = $ARGV[1] || "";
	my $source = '';

	# If there is only one param we find the DS from the env/default
	if (scalar(@ARGV) == 1 && !-f ($ARGV[0] || "")) {
		$filter = $ARGV[0] || "";
		$file   = $ENV{$SLT_ENV_VAR} || $DS_DEFAULT_FILE;

		if ($ENV{$SLT_ENV_VAR}) {
			$file   = $ENV{$SLT_ENV_VAR};
			$source = "environment variable";
		} elsif ($DS_DEFAULT_FILE) {
			$file   = $DS_DEFAULT_FILE;
			$source = "built-in default";
		}
	} elsif (scalar(@ARGV) == 0) {
		$file = $DS_DEFAULT_FILE;
		$source = "built-in default";
	} else {
		$source = "CLI parameter";
	}

	my @ret = ($file, $filter, $source);

	return @ret;
}

# Debug print variable using either Dump::Krumo (preferred) or Data::Dumper
# Creates methods k() and kd() to print, and print & die respectively
BEGIN {
	if (eval { require Dump::Krumo }) {
		Dump::Krumo->import(qw/k kd/);
	} else {
		require Data::Dumper;
		*k  = sub { print Data::Dumper::Dumper(\@_) };
		*kd = sub { print Data::Dumper::Dumper(\@_); die; };
	}
}

# vim: tabstop=4 shiftwidth=4 autoindent softtabstop=4
